name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python src/train.py
          pytest tests/

  train-and-quantize:
    runs-on: ubuntu-latest
    needs: test-suite
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train and Quantize
        run: |
          python src/train.py
          python src/quantize.py

  build-and-test-container:
    runs-on: ubuntu-latest
    needs: train-and-quantize
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t mlops-lr .

      - name: Run Container
        run: docker run --rm mlops-lr
